layout_spectrum: 0.9032258
typography_spectrum: 0.7831541
color:
  saturation: 0.3783759
  lightness: 0.2043011
  brandStrength: 0.7670251
  brandColors:
    - '#000000'
    - '#242C2F'
    - '#3C4749'
    - '#56686C'
    - '#9EB6B8'
  rhythmicContrast: 0.5755157
name: Charles Harry
